// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: proto/migrate.proto

package migrator

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MigrateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SourceUrl     string                 `protobuf:"bytes,2,opt,name=source_url,json=sourceUrl,proto3" json:"source_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MigrateRequest) Reset() {
	*x = MigrateRequest{}
	mi := &file_proto_migrate_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MigrateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MigrateRequest) ProtoMessage() {}

func (x *MigrateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_migrate_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MigrateRequest.ProtoReflect.Descriptor instead.
func (*MigrateRequest) Descriptor() ([]byte, []int) {
	return file_proto_migrate_proto_rawDescGZIP(), []int{0}
}

func (x *MigrateRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MigrateRequest) GetSourceUrl() string {
	if x != nil {
		return x.SourceUrl
	}
	return ""
}

type MigrateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MigrateResponse) Reset() {
	*x = MigrateResponse{}
	mi := &file_proto_migrate_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MigrateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MigrateResponse) ProtoMessage() {}

func (x *MigrateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_migrate_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MigrateResponse.ProtoReflect.Descriptor instead.
func (*MigrateResponse) Descriptor() ([]byte, []int) {
	return file_proto_migrate_proto_rawDescGZIP(), []int{1}
}

func (x *MigrateResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_proto_migrate_proto protoreflect.FileDescriptor

const file_proto_migrate_proto_rawDesc = "" +
	"\n" +
	"\x13proto/migrate.proto\x12\bmigrator\"?\n" +
	"\x0eMigrateRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"source_url\x18\x02 \x01(\tR\tsourceUrl\")\n" +
	"\x0fMigrateResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status2N\n" +
	"\bMigrator\x12B\n" +
	"\vMigrateData\x12\x18.migrator.MigrateRequest\x1a\x19.migrator.MigrateResponseB\x19Z\x17migrator/proto;migratorb\x06proto3"

var (
	file_proto_migrate_proto_rawDescOnce sync.Once
	file_proto_migrate_proto_rawDescData []byte
)

func file_proto_migrate_proto_rawDescGZIP() []byte {
	file_proto_migrate_proto_rawDescOnce.Do(func() {
		file_proto_migrate_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_migrate_proto_rawDesc), len(file_proto_migrate_proto_rawDesc)))
	})
	return file_proto_migrate_proto_rawDescData
}

var file_proto_migrate_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_migrate_proto_goTypes = []any{
	(*MigrateRequest)(nil),  // 0: migrator.MigrateRequest
	(*MigrateResponse)(nil), // 1: migrator.MigrateResponse
}
var file_proto_migrate_proto_depIdxs = []int32{
	0, // 0: migrator.Migrator.MigrateData:input_type -> migrator.MigrateRequest
	1, // 1: migrator.Migrator.MigrateData:output_type -> migrator.MigrateResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_migrate_proto_init() }
func file_proto_migrate_proto_init() {
	if File_proto_migrate_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_migrate_proto_rawDesc), len(file_proto_migrate_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_migrate_proto_goTypes,
		DependencyIndexes: file_proto_migrate_proto_depIdxs,
		MessageInfos:      file_proto_migrate_proto_msgTypes,
	}.Build()
	File_proto_migrate_proto = out.File
	file_proto_migrate_proto_goTypes = nil
	file_proto_migrate_proto_depIdxs = nil
}
