// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.30.2
// source: proto/migrate.proto

package migrator

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Migrator_MigrateData_FullMethodName = "/migrator.Migrator/MigrateData"
)

// MigratorClient is the client API for Migrator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MigratorClient interface {
	MigrateData(ctx context.Context, in *MigrateRequest, opts ...grpc.CallOption) (*MigrateResponse, error)
}

type migratorClient struct {
	cc grpc.ClientConnInterface
}

func NewMigratorClient(cc grpc.ClientConnInterface) MigratorClient {
	return &migratorClient{cc}
}

func (c *migratorClient) MigrateData(ctx context.Context, in *MigrateRequest, opts ...grpc.CallOption) (*MigrateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MigrateResponse)
	err := c.cc.Invoke(ctx, Migrator_MigrateData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MigratorServer is the server API for Migrator service.
// All implementations must embed UnimplementedMigratorServer
// for forward compatibility.
type MigratorServer interface {
	MigrateData(context.Context, *MigrateRequest) (*MigrateResponse, error)
	mustEmbedUnimplementedMigratorServer()
}

// UnimplementedMigratorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMigratorServer struct{}

func (UnimplementedMigratorServer) MigrateData(context.Context, *MigrateRequest) (*MigrateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MigrateData not implemented")
}
func (UnimplementedMigratorServer) mustEmbedUnimplementedMigratorServer() {}
func (UnimplementedMigratorServer) testEmbeddedByValue()                  {}

// UnsafeMigratorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MigratorServer will
// result in compilation errors.
type UnsafeMigratorServer interface {
	mustEmbedUnimplementedMigratorServer()
}

func RegisterMigratorServer(s grpc.ServiceRegistrar, srv MigratorServer) {
	// If the following call pancis, it indicates UnimplementedMigratorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Migrator_ServiceDesc, srv)
}

func _Migrator_MigrateData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MigrateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MigratorServer).MigrateData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Migrator_MigrateData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MigratorServer).MigrateData(ctx, req.(*MigrateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Migrator_ServiceDesc is the grpc.ServiceDesc for Migrator service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Migrator_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "migrator.Migrator",
	HandlerType: (*MigratorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "MigrateData",
			Handler:    _Migrator_MigrateData_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/migrate.proto",
}
